export const CLEAR_IMAGES = 'CLEAR_IMAGES';
export const RECEIVE_BANNER_FOLDER = 'RECEIVE_BANNER_FOLDER';
export const RECEIVE_FOLDERS = 'RECEIVE_FOLDERS';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
